### ISSUE TITLE
Race condition in programming

### ISSUE THREAD

**Issue by Ryzee119** [kooscode/xenium-programmer#12]
This write loop never checks the toggle bits to ensure the chip is available to receive the next write command that I can see.

https://github.com/kooscode/xenium-programmer/blob/f18a304062bf4ae3c06ad1466f5e516858a2a7da/xenium-flash/src/xenium-flash.cpp#L173

From datasheet in the Word/Byte programming section:

`
The system can determine the status of the program operation by using DQ7, DQ6, or RY/BY#. See Section 11. Write
Operation Status on page 32 for information on these status bits.
Any commands written to the device during the Embedded Program Algorithm are ignored.
`

The `std::cout` you have in the loop may slow be enough to reliably add a delay between each write to not see any issues, but the correct method would to ensure the chip is not busy before each byte I think.

**Comment by kooscode** [comment]
Thanks Ryan! I'll go check it for sure.
