### ISSUE TITLE
Error: Flash device not found

### ISSUE THREAD

**Issue by bgillman22** [kooscode/xenium-programmer#13]
I have the a Raspberry Pi Zero W with pins that I've wired to an Open Xenium chip. I am trying to write to it using the xenium-programmer script and I keep getting the 'Flash device not found' error. I have checked all of my wiring (multiple times) end to end with a multimeter and the connections appear to be correct. I can also easily pass the initial JTAG portion. Are there any suggestions or is there anything you can tell me from the included output? Many thanks!

Xenium JTAG Tool - v0.1
-----------------------
Loading JEDEC File: 
	Loaded: xenium-bin/xeniumflash.jed
	Found JED file device: XC9572XL-10-VQ64
Scanning JTAG Chain: 
	Devices found: 1
	Checking for XC9572XL: [ OK ]
	JTAG/JED Device Match: XC9572XL-10-VQ64 [ OK ]
JTAG Programming Device: 
	Erasing: [ OK ]
	Programming: [ DONE ]         
	Verifying: [ OK ]
-----------------------------
PROGRAMMING FLASH : XENIUM OS
-----------------------------
---------------------------
Xenium Flashing Tool - v0.1
---------------------------
Checking Hardware: Raspberry Pi Zero W Rev 1.1
Loading Xenium Flash BIN: xenium-bin/xenium_blue.bin
Detecting Xenium Flash: ERROR

** XENIUM FLASH DEVICE NOT FOUND - Manufacturer:187, Device:187 **

ERROR Loading XeniumOS into OpenXenium Flash memory!
Please double check your LPC Header connection and wires!

**Comment by kooscode** [comment]
It means your flash chip is not recognized.. you either did not connect the LPC pins correctly or there is a soldering short on your flash chip pins or one of the CPLD pins that connect to the flash.

i.e. this is likely a hardware issue.

**Comment by Sk1ller1993** [comment]
Hi. I'm getting the same error. I tried with both RPi 3B+ and Pi Zero W. I checked the wiring multiple times but it can't detect the flash chip.

Here is the log:

`pi@raspberrypi:~/xenium-programmer $ ./xenium-programmer
▒██   ██▒▓█████  ███▄    █  ██▓ █    ██  ███▄ ▄███▓
▒▒ █ █ ▒░▓█   ▀  ██ ▀█   █ ▓██▒ ██  ▓██▒▓██▒▀█▀ ██▒
░░  █   ░▒███   ▓██  ▀█ ██▒▒██▒▓██  ▒██░▓██    ▓██░
 ░ █ █ ▒ ▒▓█  ▄ ▓██▒  ▐▌██▒░██░▓▓█  ░██░▒██    ▒██
▒██▒ ▒██▒░▒████▒▒██░   ▓██░░██░▒▒█████▓ ▒██▒   ░██▒
▒▒ ░ ░▓ ░░░ ▒░ ░░ ▒░   ▒ ▒ ░▓  ░▒▓▒ ▒ ▒ ░ ▒░   ░  ░
░░   ░▒ ░ ░ ░  ░░ ░░   ░ ▒░ ▒ ░░░▒Programmer░     ░
 ░    ░     ░      ░   ░ ░  ▒kooscode@github   ░
 ░    ░     ░  ░         ░  ░     ░            ░
--------------------------------------
PROGRAMMING XILINX CPLD: BITBUS BRIDGE
--------------------------------------
-----------------------
Xenium JTAG Tool - v0.1
-----------------------
Loading JEDEC File:
        Loaded: xenium-bin/xeniumflash.jed
        Found JED file device: XC9572XL-10-VQ64
Scanning JTAG Chain:
        Devices found: 1
        Checking for XC9572XL: [ OK ]
        JTAG/JED Device Match: XC9572XL-10-VQ64 [ OK ]
JTAG Programming Device:
        Erasing: [ OK ]
        Programming: [ DONE ]
        Verifying: [ OK ]
-----------------------------
PROGRAMMING FLASH : XENIUM OS
-----------------------------
---------------------------
Xenium Flashing Tool - v0.1
---------------------------
Checking Hardware: Raspberry Pi 3 Model B Rev 1.2
Loading Xenium Flash BIN: xenium-bin/xenium_blue.bin
Detecting Xenium Flash: ERROR

** XENIUM FLASH DEVICE NOT FOUND - Manufacturer:187, Device:187 **

ERROR Loading XeniumOS into OpenXenium Flash memory!
Please double check your LPC Header connection and wires!
pi@raspberrypi:~/xenium-programmer $
`

**Comment by kooscode** [comment]
There is probably no issue with your wiring. the problem is a solder short or other issue with the connection between the Xilinx CPLD and your FLASH chip.

The JTAG was able to flash the Xilinx Chip and now its trying to pass through an image to the FLASH Memory chip and its failing.

i.e. this is likely a hardware issue with the OpenXenium board itself

**Comment by dtomcat** [comment]
I have a similar issue.  Hardwired the pins together (didn’t use the PCB). Triple checked for accuracy.  It programs the CPLD but fails the flash 

always Manufacturer:0, Device:0 ** (even known good chip)?

anything I can do?

**Comment by catogtp** [comment]
> I have a similar issue. Hardwired the pins together (didn’t use the PCB). Triple checked for accuracy. It programs the CPLD but fails the flash
> 
> always Manufacturer:0, Device:0 ** (even known good chip)?
> 
> anything I can do?

I had one doing this after I shut off an xbox during a recovery operation. I ended up booting a known good OX, then hotswapped. Opened xenium tools and flashed 2.3.1 to it. Then was able to program with my pi again.

**Comment by dtomcat** [comment]
i copied everything over to a new folder and re-ran ./install... and now it detects everything ok... 

now my problem is, it always fails verifying at 50% on all chips?

**Comment by kooscode** [comment]
> i copied everything over to a new folder and re-ran ./install... and now it detects everything ok...
> 
> now my problem is, it always fails verifying at 50% on all chips?

Its likely your wires are too long.  

What  PI board are you using? and also can you attach a picture of your setup?

**Comment by dtomcat** [comment]
I am using the Pi 3B+.  Attaching pictures:
![OXP1](https://user-images.githubusercontent.com/1297922/176990985-488b43bf-697c-49b1-8345-98a88e493687.jpg)
![oxp2](https://user-images.githubusercontent.com/1297922/176990990-c1cffd2c-8616-4413-aba3-068ed086fb17.jpg)

**Comment by dtomcat** [comment]
Got my boards from china and I soldered everything together... but run into same the same issue... Fails to very flash.  xenium_blue fails immediately... Ice and gold fails at 50%... I can program and use the chip in the xbox... but for some reason programming fails through PI...  again using PI3B+, I just upgraded the power supply to ensure it's getting enough power as the last power supply seemed it may not be putting out up to 3A's as stated.  Not sure what's wrong here as it's working for others.  If I can figure this out, I have plans to make a couple of different PCBs to help give back to the community.

The LEDs are working as advertised (great job).  my next step is programming buttons into this, but kind of pointless if I can't get it work...    Thanks for any help.

**Comment by dtomcat** [comment]
I tried re-installing again... but same results

**Comment by dtomcat** [comment]
Might it be a timing issue, do i need to set my pi up for a certain speed?

**Comment by dtomcat** [comment]
My progress on the board:

https://youtu.be/mwh13RN9auk

thoughts?  If you like it… I’ll clean it up… document install process and do a pull request

sorry for AC noise in background and low quality. I uploaded in 1080, but YT thought it was better in 240p

**Comment by dtomcat** [comment]
Which OS does everyone that had success use?  maybe that's why mine fails?  not sure  trying a pi zero now if I can get past "package wiringpi has no installation candidate"
