### ISSUE TITLE
More board information

### ISSUE THREAD

**Issue by dtomcat** [kooscode/xenium-programmer#14]
Hello,
   I'm looking at making this board, but unable to find any information about it.  I downloaded the zip file and can see the gbr files, but it appears the BOM just says resistor... which value?, LEDs 5MM, but which 5MM?

also what do the buttons do?  Do i need to add the LEDs, Resistors, pin headers, etc If I will use SSH? (obviously i need the jtag header and LPC header. and power header.

Was this board wishful thinking for future that never developed?  Thank you for any information.

**Comment by kooscode** [comment]
The LEDs do work.   the current limiting resistors will depend on what LED you use.  if you go for standard 5mm LED, just use  a 440 Ohm resistor and you should be fine. 

The buttons are for future head-less design.  you are welcome to contribute to the open source code-base and enable them for yourself and everyone else if you would like.


The board is  working well on my and many other user's setups, glad you are experimenting with it and hope you get yours working.

**Comment by dtomcat** [comment]
Thank you for the information.  I'm sorry if that came across as rude/uncalled for... wasn't my intent.  If I were able to code for the Pi, I most definitely would contribute; however, I'm not very fluent in coding for Pi.  I may order a set of PCBs and play around with it... I may just do some homework and code in the buttons.

Again, Thank you for the information.

**Comment by dtomcat** [comment]
Also, can you point me to where in the code that it controls the LEDs?  I looked, but can’t find it. Sorry. I ordered a few boards from china… so I should have button code in about 30ish days 🤞🏻

**Comment by kooscode** [comment]
> Also, can you point me to where in the code that it controls the LEDs? I looked, but can’t find it. Sorry. I ordered a few boards from china… so I should have button code in about 30ish days 🤞🏻

I realized it was never checked in.. here is a the Python wrapper for the programmer that includes LED support.

LED1 = OK
LED2 = BUSY
LED3 = ERROR

https://github.com/kooscode/xenium-programmer/blob/main/xenium-programmer-pi

**Comment by dtomcat** [comment]
Thank you

**Comment by dtomcat** [comment]
@kooscode,  here is what I have so far.  I need to clean up the code a bit, and work on 3d case a bit... but working great.
[Youtube video of new board in action](https://youtu.be/z7_i9MSSPrc)

**Comment by dtomcat** [comment]
@kooscode I've made a new board...  Can't really be pulled as I had to change the way the code works for this specific board.  But wanted to give you a heads up since I can't put in a pull request.  Thank you!

https://github.com/dtomcat/XP-chip
